/*
 * generated by Xtext
 */
package unige.dibris;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class KPLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return unige.dibris.ui.internal.KPLActivator.getInstance().getInjector("unige.dibris.KPL");
	}
	
}
