/*
 * generated by Xtext
 */
package unige.dibris.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KPLUiModule extends unige.dibris.ui.AbstractKPLUiModule {
	public KPLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
