/*
 * generated by Xtext
 */
package unige.dibris;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KPLRuntimeModule extends unige.dibris.AbstractKPLRuntimeModule {

}
