/*
 * generated by Xtext
 */
package unige.dibris;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class KPLStandaloneSetup extends KPLStandaloneSetupGenerated{

	public static void doSetup() {
		new KPLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

