/*
 * generated by Xtext
 */
package unige.dibris.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractKPLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(unige.dibris.kPL.KPLPackage.eINSTANCE);
		return result;
	}
}
