/*
 * generated by Xtext
 */
package unige.dibris.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import unige.dibris.ui.internal.KPLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KPLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KPLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KPLActivator.getInstance().getInjector(KPLActivator.UNIGE_DIBRIS_KPL);
	}
	
}
